const SuggestBoxDetails = [
  {
    id: 1,
    title: "مهندسی نرم افزار",
    subTitle: "23 دوره آموزشی",
    img: "./assests/images/suggested/content.png",
    backgroundColor: "#e5f7f8",
    titleColor: "#00adb6",
  },
  {
    id: 2,
    title: "کسب و کار",
    subTitle: "58 دوره آموزشی",
    img: "./assests/images/suggested/briefcase.png",
    backgroundColor: "#fef7e8",
    titleColor: "#f7b320",
  },
  {
    id: 3,
    title: "حسابداری",
    subTitle: "74 دوره آموزشی",
    img: "./assests/images/suggested/career.png",
    backgroundColor: "#f5fcec",
    titleColor: "#f10750",
  },
  {
    id: 4,
    title: "برنامه نویسی وب",
    subTitle: "65 دوره آموزشی",
    img: "./assests/images/suggested/python.png",
    backgroundColor: "#f5fcec",
    titleColor: "#9ade45",
  },
  {
    id: 5,
    title: "طراحی و گرافیک",
    subTitle: "43 دوره آموزشی",
    img: "./assests/images/suggested/designer.png",
    backgroundColor: "#e6fbfd",
    titleColor: "#0dd6ea",
  },
  {
    id: 6,
    title: "بورس بازار و سهام",
    subTitle: "82 دوره آموزشی",
    img: "./assests/images/suggested/speaker.png",
    backgroundColor: "#f8efff",
    titleColor: "#b95ffd",
  },
  {
    id: 7,
    title: "هنر و عکاسی",
    subTitle: "25 دوره آموزشی",
    img: "./assests/images/suggested/photo.png",
    backgroundColor: "#FDEDF4",
    titleColor: "#ec5098",
  },
  {
    id: 8,
    title: "ورزش و سلامتی",
    subTitle: "43 دوره آموزشی",
    img: "./assests/images/suggested/health.png",
    backgroundColor: "#E9F6EF",
    titleColor: "#25a55f",
  },
  {
    id: 9,
    title: "سبک زندگی",
    subTitle: "38 دوره آموزشی",
    img: "./assests/images/suggested/yoga.png",
    backgroundColor: "#FDF0E6",
    titleColor: "#ea690d",
  },
];

export default SuggestBoxDetails;