const PopularCoursesDatas = [
  {
    id: 1,
    img: './assests/images/popular/co-2.jpg',
    title: "آموزش ASP.Net ساخت سایت شخصی",
    teacher: "حسین راد",
    count: "11",
    rate: "4.9",
    category: "برنامه نویسی",
    categoryColor: " #00bcd4;",
    categoryBg: "rgba(0, 188, 212,0.1)",
    price: "890",
  },
  {
    id: 2,
    img: './assests/images/popular/co-3.jpg',
    title: "آموزش ساخت ربات تلگرام با PHP",
    teacher: "علی خسروجردی",
    count: "13 ",
    rate: "4.6",
    category: "حسابداری",
    categoryColor: "#ff5722",
    categoryBg: "rgba(255, 87, 34,0.1)",
    price: "510",
  },
  {
    id: 3,
    img: './assests/images/popular/co-4.jpg',
    title: "آموزش برنامه نویسی‌اندروید",
    teacher: "مسعود زارعی",
    count: "15",
    rate: "4.7",
    category: "استارت آپ",
    categoryColor: "#e91e63",
    categoryBg: "rgba(233, 30, 99,0.1)",
    price: "549",
  },
  {
    id: 4,
    img: './assests/images/popular/co-5.jpg',
    title: "آموزش تبدیل PSD به HTML (یک)",
    teacher: "نیلوفر کشاورز",
    count: "16",
    rate: "4.9",
    category: "گرافیک",
    categoryColor: "#8bc34a",
    categoryBg: "rgba(139, 195, 74,0.1)",
    price: "449",
  },
  {
    id: 5,
    img: './assests/images/popular/co-6.jpg',
    title: "آموزش کار با وکتور در فتوشاپ",
    teacher: "الهام کریمی",
    count: "10",
    rate: "4.8",
    category: "انیمیشن",
    categoryColor: "#9b59d6",
    categoryBg: "rgba(155, 89, 214,0.1",
    price: "599",
  },
  {
    id: 6,
    img: './assests/images/popular/co-7.jpg',
    title: "آموزش طراحی قالب ریسپانسیو",
    teacher: "مهرداد نوروزی",
    count: "12",
    rate: "4.7",
    category: "طراحی سایت",
    categoryColor: "#2196f3",
    categoryBg: "rgb(33, 150, 243,0.1",
    price: "700",
  },
];

export default PopularCoursesDatas;